services:
  - type: web
    name: capmap-web
    env: node
    rootDir: .
    buildCommand: pnpm install; pnpm build
    startCommand: pnpm start
    healthCheckPath: /health
    healthCheckIntervalSeconds: 5
    healthCheckTimeoutSeconds: 5
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
