import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'login.title': 'Welcome to CapMap',
    'login.subtitle': 'Sign in to access your capability maps',
    'login.email': 'Email Address',
    'login.submit': 'Sign In',
    'login.demo': 'Try Demo',
    'nav.dashboard': 'Dashboard',
    'nav.capabilities': 'Capabilities',
    'nav.visualization': 'Visualization',
    'nav.processes': 'Processes',
    'nav.upload': 'Upload Data',
    'nav.export': 'Export',
    'nav.settings': 'Settings',
    'nav.logout': 'Sign Out',
    'demo.mode': 'Interactive Demo',
    'demo.exit': 'Exit',
    'demo.step1.title': 'Step 1: Upload Dataset',
    'demo.step1.desc': 'Let\'s answer that. We\'ll start by loading a sample dataset containing your IT systems and capabilities.',
    'demo.step1.btn': 'Load Demo Dataset',
    'demo.step2.title': 'Step 2: Capability Graph',
    'demo.step2.desc': 'CapMap has mapped your IT systems to capabilities. Notice how Customer Management is supported by multiple systems.',
    'demo.step2.btn': 'Generate Metrics',
    'demo.step3.title': 'Step 3: Metrics Generation',
    'demo.step3.desc': 'AI has generated metrics for each capability. Let\'s look at Order Processing.',
    'demo.step3.btn': 'Find Bottlenecks',
    'demo.step4.title': 'Step 4: Bottleneck Detection',
    'demo.step4.desc': 'Now look at Customer Management. CapMap detected overlapping systems (Salesforce + Legacy CRM).',
    'demo.step4.btn': 'View Modernization Plan',
    'demo.step5.title': 'Step 5: Modernization Opportunities',
    'demo.step5.desc': 'Here is the projected outcome if you retire the Legacy CRM.',
    'demo.step5.btn': 'Visualize Value Paths',
    'demo.step6.title': 'Step 6: Value Delivery Paths',
    'demo.step6.desc': 'You can generate architectural diagrams to visualize these dependencies and communicate the modernization plan to stakeholders.',
    'demo.step6.btn': 'Export Insights',
    'demo.step7.title': 'Step 7: Export Insights',
    'demo.step7.desc': 'Finally, export your capability metrics and modernization priorities as a CSV or Excel report.',
    'demo.step7.btn': 'Finish Demo',
    'dashboard.title': 'Executive Dashboard',
    'dashboard.desc': 'Real-time KPI summary and capability health overview.',
    'dashboard.total_cap': 'Total Capabilities',
    'dashboard.maturity': 'Maturity Index',
    'dashboard.ai_gen': 'AI Generations',
    'dashboard.daily_limit': 'Daily Limit',
    'dashboard.growth': 'Capability Growth',
    'dashboard.domain_dist': 'Domain Distribution',
    'dashboard.health': 'System Health',
    'dashboard.trend': 'Capability Maturity Trend',
    'dashboard.insights': 'AI Insights',
    'dashboard.view_report': 'View Full Report',
    'cap.title': 'Capability Map',
    'cap.desc': 'Hierarchical view of business capabilities and their supporting systems.',
    'cap.empty': 'No capabilities found. Add one to get started.',
    'cap.metrics_title': 'Metrics:',
    'cap.metrics_empty': 'Select a capability to view AI-generated metrics.',
    'cap.no_selection': 'No Capability Selected',
    'cap.no_selection_desc': 'Click on a capability from the list to view its detailed metrics and KPIs.',
    'cap.filter': 'Filter by domain...',
    'cap.new': 'New Capability',
    'cap.systems': 'Systems',
    'cap.score': 'Score',
    'cap.auto': 'Auto',
    'viz.title': 'AI Visualization',
    'viz.desc': 'Generate architectural diagrams and capability maps using Gemini.',
    'viz.builder': 'Prompt Builder',
    'viz.type': 'Diagram Type',
    'viz.context': 'Context / Description',
    'viz.generate': 'Generate Visualization',
    'viz.preview': 'Output Preview',
    'viz.download': 'Download Image',
    'viz.loading': 'Gemini is crafting your visualization...',
    'viz.empty': 'Your generated diagram will appear here.',
    'viz.tpl.cap_map.name': 'Capability Map',
    'viz.tpl.cap_map.prompt': 'A multi-layered capability map for a retail organization focusing on supply chain and logistics. Highlight core capabilities like Inventory Management, Order Fulfillment, and Warehouse Operations. Use a clean, modern corporate style with distinct color coding for different domains.',
    'viz.tpl.val_chain.name': 'Value Chain',
    'viz.tpl.val_chain.prompt': 'A Porter\'s Value Chain diagram for a SaaS company. Show primary activities: Inbound Logistics, Operations, Outbound Logistics, Marketing & Sales, and Service. Show support activities: Firm Infrastructure, HR Management, Technology Development, and Procurement. Use a professional, flat design style.',
    'viz.tpl.dep_graph.name': 'Dependency Graph',
    'viz.tpl.dep_graph.prompt': 'A complex IT system dependency graph showing the relationship between a legacy CRM, a modern cloud-based Order Processing system (AWS Lambda), and a Data Warehouse (Snowflake). Highlight data flow bottlenecks and high-coupling areas with red warning indicators. Technical architecture diagram style.',
    'upload.title': 'Data Ingestion',
    'upload.desc': 'Upload your system inventory or capability models for AI processing.',
    'upload.drag': 'Drag and drop your file here',
    'upload.support': 'Supports CSV, JSON, or Excel (Max 50MB)',
    'upload.browse': 'Browse Files',
    'upload.btn': 'Process Data',
    'upload.success': 'Upload Successful',
    'upload.processed': 'processed successfully.',
    'export.title': 'Export & Reports',
    'export.desc': 'Generate comprehensive reports and export your capability data.',
    'export.format': 'Export Format',
    'export.content': 'Content to Export',
    'export.btn': 'Generate Export',
    'export.csv.title': 'CSV Export',
    'export.csv.desc': 'Raw data export containing all capabilities, domains, maturity levels, and generated metrics.',
    'export.csv.btn': 'Download CSV',
    'export.xlsx.title': 'Excel Report',
    'export.xlsx.desc': 'Formatted spreadsheet with capability metrics, ready for executive presentations and analysis.',
    'export.xlsx.btn': 'Download XLSX',
    'coming_soon': 'Process mapping and linking is coming soon.',
    'settings.desc': 'Manage your profile and API usage quotas.',
    'login.terms': 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    'onboarding.step1.title': 'Welcome to CapMap AI',
    'onboarding.step1.desc': 'Let\'s get you started with a quick tour of the platform.',
    'onboarding.step1.btn': 'Next',
    'onboarding.step2.title': 'Upload Your Data',
    'onboarding.step2.desc': 'Start by uploading your business capability dataset here.',
    'onboarding.step2.btn': 'Go to Upload',
    'onboarding.step3.title': 'Generate Metrics',
    'onboarding.step3.desc': 'Navigate to Capabilities to view your map and generate AI-powered KPIs.',
    'onboarding.step3.btn': 'Go to Capabilities',
    'onboarding.step4.title': 'AI Visualization',
    'onboarding.step4.desc': 'Finally, use Gemini to create professional architectural diagrams.',
    'onboarding.step4.btn': 'Go to Visualization',
    'onboarding.step5.title': 'All Set!',
    'onboarding.step5.desc': 'You\'re ready to map your enterprise. Enjoy the power of CapMap AI.',
    'onboarding.step5.btn': 'Finish',
    'onboarding.skip': 'Skip Tutorial',
    'onboarding.step': 'Step',
    'onboarding.of': 'of',
    'demo.step1.quote': '"Which technologies are slowing down the business — and what should we modernize first?"',
    'demo.step2.insight': 'Insight:',
    'demo.step2.insight_text': 'Overlapping systems often indicate technical debt.',
    'demo.step3.powered': 'Powered by:',
    'demo.step3.auto_ratio': 'Automation Ratio:',
    'demo.step3.op_eff': 'Operational Efficiency:',
    'demo.step3.high': '(High)',
    'demo.step4.coupling': 'System Coupling:',
    'demo.step4.priority': 'Modernization Priority:',
    'demo.step4.high': 'High',
    'demo.step5.current': 'Current State',
    'demo.step5.action': 'Recommended Action',
    'demo.step5.action_text': 'Retire Legacy CRM',
    'demo.step5.outcome': 'Projected Outcome',
  },
  ar: {
    'login.title': 'مرحباً بك في CapMap',
    'login.subtitle': 'سجل الدخول للوصول إلى خرائط القدرات الخاصة بك',
    'login.email': 'البريد الإلكتروني',
    'login.submit': 'تسجيل الدخول',
    'login.demo': 'جرب النسخة التجريبية',
    'nav.dashboard': 'لوحة القيادة',
    'nav.capabilities': 'القدرات',
    'nav.visualization': 'التصور',
    'nav.processes': 'العمليات',
    'nav.upload': 'رفع البيانات',
    'nav.export': 'تصدير',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'demo.mode': 'العرض التفاعلي',
    'demo.exit': 'خروج',
    'demo.step1.title': 'الخطوة 1: رفع البيانات',
    'demo.step1.desc': 'دعنا نجيب على ذلك. سنبدأ بتحميل مجموعة بيانات نموذجية تحتوي على أنظمة تكنولوجيا المعلومات والقدرات الخاصة بك.',
    'demo.step1.btn': 'تحميل بيانات العرض',
    'demo.step2.title': 'الخطوة 2: رسم بياني للقدرات',
    'demo.step2.desc': 'قامت CapMap بتعيين أنظمة تكنولوجيا المعلومات الخاصة بك إلى القدرات. لاحظ كيف يتم دعم إدارة العملاء بواسطة أنظمة متعددة.',
    'demo.step2.btn': 'توليد المقاييس',
    'demo.step3.title': 'الخطوة 3: توليد المقاييس',
    'demo.step3.desc': 'قام الذكاء الاصطناعي بتوليد مقاييس لكل قدرة. دعنا نلقي نظرة على معالجة الطلبات.',
    'demo.step3.btn': 'البحث عن الاختناقات',
    'demo.step4.title': 'الخطوة 4: اكتشاف الاختناقات',
    'demo.step4.desc': 'الآن انظر إلى إدارة العملاء. اكتشفت CapMap أنظمة متداخلة (Salesforce + Legacy CRM).',
    'demo.step4.btn': 'عرض خطة التحديث',
    'demo.step5.title': 'الخطوة 5: فرص التحديث',
    'demo.step5.desc': 'إليك النتيجة المتوقعة إذا قمت بإيقاف تشغيل Legacy CRM.',
    'demo.step5.btn': 'تصور مسارات القيمة',
    'demo.step6.title': 'الخطوة 6: مسارات تقديم القيمة',
    'demo.step6.desc': 'يمكنك إنشاء مخططات معمارية لتصور هذه التبعيات وتوصيل خطة التحديث لأصحاب المصلحة.',
    'demo.step6.btn': 'تصدير الرؤى',
    'demo.step7.title': 'الخطوة 7: تصدير الرؤى',
    'demo.step7.desc': 'أخيرًا، قم بتصدير مقاييس القدرات وأولويات التحديث كتقرير CSV أو Excel.',
    'demo.step7.btn': 'إنهاء العرض',
    'dashboard.title': 'لوحة القيادة التنفيذية',
    'dashboard.desc': 'ملخص مؤشرات الأداء الرئيسية في الوقت الفعلي ونظرة عامة على صحة القدرات.',
    'dashboard.total_cap': 'إجمالي القدرات',
    'dashboard.maturity': 'مؤشر النضج',
    'dashboard.ai_gen': 'توليد الذكاء الاصطناعي',
    'dashboard.daily_limit': 'الحد اليومي',
    'dashboard.growth': 'نمو القدرات',
    'dashboard.domain_dist': 'توزيع المجال',
    'dashboard.health': 'صحة النظام',
    'dashboard.trend': 'اتجاه نضج القدرات',
    'dashboard.insights': 'رؤى الذكاء الاصطناعي',
    'dashboard.view_report': 'عرض التقرير الكامل',
    'cap.title': 'خريطة القدرات',
    'cap.desc': 'عرض هرمي لقدرات الأعمال والأنظمة الداعمة لها.',
    'cap.empty': 'لم يتم العثور على قدرات. أضف واحدة للبدء.',
    'cap.metrics_title': 'المقاييس:',
    'cap.metrics_empty': 'حدد قدرة لعرض المقاييس التي تم إنشاؤها بواسطة الذكاء الاصطناعي.',
    'cap.no_selection': 'لم يتم تحديد قدرة',
    'cap.no_selection_desc': 'انقر فوق قدرة من القائمة لعرض مقاييسها التفصيلية ومؤشرات الأداء الرئيسية.',
    'cap.filter': 'تصفية حسب المجال...',
    'cap.new': 'قدرة جديدة',
    'cap.systems': 'الأنظمة',
    'cap.score': 'النتيجة',
    'cap.auto': 'تلقائي',
    'viz.title': 'تصور الذكاء الاصطناعي',
    'viz.desc': 'إنشاء مخططات معمارية وخرائط قدرات باستخدام Gemini.',
    'viz.builder': 'منشئ المطالبات',
    'viz.type': 'نوع المخطط',
    'viz.context': 'السياق / الوصف',
    'viz.generate': 'توليد التصور',
    'viz.preview': 'معاينة المخرجات',
    'viz.download': 'تنزيل الصورة',
    'viz.loading': 'يقوم Gemini بصياغة التصور الخاص بك...',
    'viz.empty': 'سيظهر المخطط الذي تم إنشاؤه هنا.',
    'viz.tpl.cap_map.name': 'خريطة القدرات',
    'viz.tpl.cap_map.prompt': 'خريطة قدرات متعددة الطبقات لمؤسسة بيع بالتجزئة تركز على سلسلة التوريد والخدمات اللوجستية. قم بإبراز القدرات الأساسية مثل إدارة المخزون وتلبية الطلبات وعمليات المستودعات. استخدم أسلوبًا مؤسسيًا حديثًا ونظيفًا مع ترميز لوني مميز للمجالات المختلفة.',
    'viz.tpl.val_chain.name': 'سلسلة القيمة',
    'viz.tpl.val_chain.prompt': 'مخطط سلسلة القيمة لبورتر لشركة SaaS. أظهر الأنشطة الأساسية: الخدمات اللوجستية الواردة، العمليات، الخدمات اللوجستية الصادرة، التسويق والمبيعات، والخدمة. أظهر الأنشطة الداعمة: البنية التحتية للشركة، إدارة الموارد البشرية، تطوير التكنولوجيا، والمشتريات. استخدم أسلوب تصميم احترافي ومسطح.',
    'viz.tpl.dep_graph.name': 'رسم بياني للتبعية',
    'viz.tpl.dep_graph.prompt': 'مخطط تبعية نظام تكنولوجيا المعلومات المعقد يوضح العلاقة بين نظام CRM القديم ونظام معالجة الطلبات الحديث القائم على السحابة (AWS Lambda) ومستودع البيانات (Snowflake). قم بإبراز اختناقات تدفق البيانات ومناطق الاقتران العالي بمؤشرات تحذير حمراء. أسلوب مخطط الهندسة التقنية.',
    'upload.title': 'استيعاب البيانات',
    'upload.desc': 'قم بتحميل مخزون النظام الخاص بك أو نماذج القدرات لمعالجة الذكاء الاصطناعي.',
    'upload.drag': 'اسحب وأفلت الملف هنا',
    'upload.support': 'يدعم CSV أو JSON أو Excel (بحد أقصى 50 ميجابايت)',
    'upload.browse': 'تصفح الملفات',
    'upload.btn': 'معالجة البيانات',
    'upload.success': 'تم الرفع بنجاح',
    'upload.processed': 'تمت المعالجة بنجاح.',
    'export.title': 'التصدير والتقارير',
    'export.desc': 'إنشاء تقارير شاملة وتصدير بيانات القدرات الخاصة بك.',
    'export.format': 'تنسيق التصدير',
    'export.content': 'المحتوى المراد تصديره',
    'export.btn': 'إنشاء تصدير',
    'export.csv.title': 'تصدير CSV',
    'export.csv.desc': 'تصدير البيانات الأولية التي تحتوي على جميع القدرات والمجالات ومستويات النضج والمقاييس التي تم إنشاؤها.',
    'export.csv.btn': 'تنزيل CSV',
    'export.xlsx.title': 'تقرير Excel',
    'export.xlsx.desc': 'جدول بيانات منسق بمقاييس القدرات، جاهز للعروض التقديمية والتحليلات التنفيذية.',
    'export.xlsx.btn': 'تنزيل XLSX',
    'coming_soon': 'رسم خرائط العمليات والربط قريباً.',
    'settings.desc': 'إدارة ملفك الشخصي وحصص استخدام واجهة برمجة التطبيقات.',
    'login.terms': 'من خلال الاستمرار، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا.',
    'onboarding.step1.title': 'مرحباً بك في CapMap AI',
    'onboarding.step1.desc': 'دعنا نبدأ بجولة سريعة في المنصة.',
    'onboarding.step1.btn': 'التالي',
    'onboarding.step2.title': 'رفع بياناتك',
    'onboarding.step2.desc': 'ابدأ برفع مجموعة بيانات قدرات عملك هنا.',
    'onboarding.step2.btn': 'الذهاب إلى الرفع',
    'onboarding.step3.title': 'توليد المقاييس',
    'onboarding.step3.desc': 'انتقل إلى القدرات لعرض خريطتك وإنشاء مؤشرات أداء رئيسية مدعومة بالذكاء الاصطناعي.',
    'onboarding.step3.btn': 'الذهاب إلى القدرات',
    'onboarding.step4.title': 'تصور الذكاء الاصطناعي',
    'onboarding.step4.desc': 'أخيرًا، استخدم Gemini لإنشاء مخططات معمارية احترافية.',
    'onboarding.step4.btn': 'الذهاب إلى التصور',
    'onboarding.step5.title': 'كل شيء جاهز!',
    'onboarding.step5.desc': 'أنت جاهز لرسم خريطة مؤسستك. استمتع بقوة CapMap AI.',
    'onboarding.step5.btn': 'إنهاء',
    'onboarding.skip': 'تخطي البرنامج التعليمي',
    'onboarding.step': 'الخطوة',
    'onboarding.of': 'من',
    'demo.step1.quote': '"ما هي التقنيات التي تبطئ العمل - وما الذي يجب علينا تحديثه أولاً؟"',
    'demo.step2.insight': 'رؤية:',
    'demo.step2.insight_text': 'غالباً ما تشير الأنظمة المتداخلة إلى ديون تقنية.',
    'demo.step3.powered': 'مدعوم بواسطة:',
    'demo.step3.auto_ratio': 'نسبة الأتمتة:',
    'demo.step3.op_eff': 'الكفاءة التشغيلية:',
    'demo.step3.high': '(عالي)',
    'demo.step4.coupling': 'اقتران النظام:',
    'demo.step4.priority': 'أولوية التحديث:',
    'demo.step4.high': 'عالي',
    'demo.step5.current': 'الحالة الحالية',
    'demo.step5.action': 'الإجراء الموصى به',
    'demo.step5.action_text': 'إيقاف نظام CRM القديم',
    'demo.step5.outcome': 'النتيجة المتوقعة',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};